### PR TITLE
Emscripten 2 fix for makeDynCall

### PR DESCRIPTION
**Pull request by JCash**

### CODE REVIEW

**Comment by AGulev** [comment]
According to this change log, pointer should be 

>New syntax for calling Wasm function pointers from JS library files is
>{{{ makeDynCall('sig', 'ptr') }}} (arg1, arg2);

https://github.com/emscripten-core/emscripten/blob/master/ChangeLog.md#203-09102020

**Comment by JCash** [comment]
Perhaps. That's the curious part. What _is_ the name here? In the glfw case it was:

> {{{ makeDynCall('vii', 'GLFW.mousePosFunc') }}}(lastX, lastY);

But what should it be here? We have no string name for the function itself.
In this case, I leaned on a small snippet from one of the maintainers:

https://github.com/emscripten-core/emscripten/issues/10039#issuecomment-565750111

But, since I'm unable to verify myself locally, I need someone else to do it.

**Comment by AGulev** [comment]
afk right now, I'll try to check today later or tomorrow

**Comment by britzl** [comment]
This seems to work:

```
{{{ makeDynCall('viiii', 'callback') }}}(thread, state_closed, errbuf, 0);
```

**Review by britzl — APPROVED** [review]

**Pull request merged**
