### PR TITLE
Update to 17.0.0

### PR DESCRIPTION
**Pull request by AGulev**
fix https://github.com/defold/extension-facebook/issues/57

### CODE REVIEW

**Comment by AGulev** [comment]
UPD: I found another phone for tests, and it seems like there is an issue with that 
Login is fine, but when I try to get name I have 
image

I'm looking into it now

**Comment by AGulev** [comment]
@britzl now it's ready for review

**Comment by AGulev** [comment]
a bit of context for the future:

Now there are two types of login `FBSDKLoginTrackingLimited` and `FBSDKLoginTrackingEnabled`
`FBSDKLoginTrackingEnabled` - this is current type of login
`FBSDKLoginTrackingLimited` - new one which doesn’t provide token (actually you can get it, but if you try to use it - it’s invalid) you can use with Graph API  instead it provides AuthenticationToken you can use for login

Also, all the data was requested with permissions will be available in `FBSDKProfile.currentProfile`

ObjC example:
```ObjC
 FBSDKLoginManager *loginManager = [FBSDKLoginManager new];
FBSDKLoginConfiguration *configuration =
  [[FBSDKLoginConfiguration alloc] initWithPermissions:@[@"email", @"user_friends", @"user_birthday", @"user_age_range", @"user_hometown", @"user_location", @"user_gender", @"user_link"]
                                              tracking:FBSDKLoginTrackingLimited
                                                 nonce:@"123"];
[loginManager logInFromViewController:self
                        configuration:configuration
                           completion:^(FBSDKLoginManagerLoginResult * result, NSError *error) {
  if (!error && !result.isCancelled) {
    // Login successful

    // getting user ID
    NSString *userID =
      FBSDKProfile.currentProfile.userID;

    // getting id token string
    NSString *idTokenString =
      FBSDKAuthenticationToken.currentAuthenticationToken.tokenString;

    // fetching pre-populated email
    NSString *email = FBSDKProfile.currentProfile.email;
  
    // getting pre-populated friends list
    NSArray<FBSDKUserIdentifier *> *friendIDs = FBSDKProfile.currentProfile.friendIDs;

    // getting pre-populated user birthday
    NSDate *birthday = FBSDKProfile.currentProfile.birthday;

    // getting pre-populated age range
    FBSDKUserAgeRange *ageRange = FBSDKProfile.currentProfile.ageRange;  
  
    // getting pre-populated age range
    FBSDKLocation *hometown = FBSDKProfile.currentProfile.hometown;  
  
    // getting pre-populated age range
    FBSDKLocation *location = FBSDKProfile.currentProfile.location;  
  
    // getting pre-populated age range
    NSString *gender = FBSDKProfile.currentProfile.gender;  
  
    // getting pre-populated age range
    NSURL *userLink = FBSDKProfile.currentProfile.linkURL;  
  }
}];
```

What's done:
* a way to use `FBSDKLoginTrackingLimited` as a separate Lua function 
* a way to get `FBSDKProfile.currentProfile` data 
* a way to get` FBSDKAuthenticationToken.currentAuthenticationToken`
 ----

**Review by britzl — APPROVED** [review]
Looks good!

**Pull request merged**
